packages:
  - packages/*
  - packages/tiny-sql/examples/*
  - packages/tiny-react/examples/*
  - packages/theme-script/examples/*
  - packages/tiny-refresh/examples/*
  - packages/utils-node/examples/*
