version: "3.5"

services:
  postgres:
    image: postgres:alpine
    ports:
      - 6432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 1s
      retries: 10

volumes:
  postgres-volume:
