name: ci
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint-check
      - run: pnpm build
      - run: pnpm tsc
      - run: pnpm test
      - run: npx typedoc
