name: ci
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          build: false
          playwright: false
      - run: pnpm lint-check
      - run: pnpm build
      - run: pnpm tsc
      - run: pnpm test

  tiny-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm -C packages/tiny-react/examples/server test-e2e
      - run: pnpm -C packages/tiny-react/examples/server build
      - run: pnpm -C packages/tiny-react/examples/server test-e2e-preview

  tiny-refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm -C packages/tiny-refresh/examples/react test-e2e
      - run: pnpm -C packages/tiny-refresh/examples/react test-e2e-webpack
